version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -Dmaven.test.skip=true 
artifacts:
  files:
    - target/aws-boot-demo-0.0.1.war
    - appspec.yml
  discard-paths: yes
